version: 2.1

orbs:
  codecov: codecov/codecov@3.2.4
jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
      - codecov/upload

      - run:
          name: CheckStyle
          command: mvn -DskipTests checkstyle:checkstyle


workflows:
  build-and-test:
    jobs:
      - build-and-test:
          filters:
            branches:
              only:
                - master